---
name: WWW-Rafb-Create
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: create new pastes on http://rafb.net
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::Rafb::Create:
    file: lib/WWW/Rafb/Create.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
